### ISSUE TITLE
Add test coverage task list

### ISSUE THREAD

**Issue by davefollett** [dance2die/calendar-dates#54]
## Test Coverage tasks
- [x] Add test coverage flag to Jest: [reference](https://jestjs.io/docs/en/cli.html#coverage)
- [x] Add Code Climate configuration to CircleCI: [example](https://docs.codeclimate.com/docs/circle-ci-test-coverage-example) 
- [x] Add Code Climate test coverage badge: [markdown](https://codeclimate.com/github/dance2die/calendar-dates/badges)

## Validate CircleCI configuration file
- [x] Install CircleCI CLI - [documentation](https://circleci.com/docs/2.0/local-cli/#installation)
- [x] Validate CircleCI using CLI - [documentation](https://circleci.com/docs/2.0/local-cli/#validate-a-circleci-config)

**Comment by dance2die** [comment]
PR #55 took care of this issue.
Thanks @davefollett again for the wonderful issue (and links to docs) 🙏.
